import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ProductFormProvider } from './context/ProductFormContext';
import Script from 'next/script';

const geistSans = Geist({
   variable: '--font-geist-sans',
   subsets: ['latin'],
});

const geistMono = Geist_Mono({
   variable: '--font-geist-mono',
   subsets: ['latin'],
});

export const metadata: Metadata = {
   title: 'Candle Bliss',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang='en' suppressHydrationWarning>
         <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <ProductFormProvider>{children}</ProductFormProvider>
            <Script id="suppress-scroll-warning" strategy="afterInteractive">
               {`
               // Disable Next.js auto-scroll warnings for fixed elements
               window.__NEXT_SCROLL_RESTORATION = false;
               `}
            </Script>
         </body>
      </html>
   );
}
